<!DOCTYPE html>
<html lang="">
    <head>
        <meta charset="utf-8" />
        <title></title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="assets/css/style.css" type="text/css"/>
    </head>
    <body>
        <?php
            require "templates/partials/_header.phtml";
            require "templates/$template.phtml";
            require "templates/partials/_footer.phtml";
        ?>
    </body>
</html>